FROM golang:1.14 AS builder
WORKDIR /build
ADD main.go main.go
ADD go.mod go.mod
ADD cmd cmd
ADD pkg pkg

# Fetch dependencies
RUN go mod download

# Build image as a truly static Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /command-line -a -tags netgo -ldflags '-s -w' .

FROM alpine/git
MAINTAINER Jadson Medeiros <developer@gmail.com>
COPY --from=builder /command-line /command-line
ENTRYPOINT ["/command-line"]
